export { default as Chat } from './Chat'
export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as Error404 } from './Errors/Error404'
export { default as Landing } from './Others/Landing'
export { default as ScreenAvatar } from './Avatar'
